### ISSUE TITLE
[Bug / 1.0(0) / 우선순위 높음] StoreDetail 버그 수정

### ISSUE THREAD

**Issue by sero3779** [YAPP-Github/21st-ALL-Rounder-Team-1-iOS#134]
## 📝 todo
- [ ] 이 매장의 좋은 점 카드와 리뷰 타이틀 사이에 디바이더가 사라진 오류 수정
- [ ] (리뷰) 태그 일부가 잘리는 오류 수정
- [ ] 태그 콜렉션뷰의 크기가 제대로 나오지 않는 오류 수정
