### ISSUE TITLE
[QA] 1.0(10) 대응

### ISSUE THREAD

**Issue by sero3779** [YAPP-Github/21st-ALL-Rounder-Team-1-iOS#171]
## 🐞 버그 설명
디자인 요구사항과 다른 백버튼의 위치를 조정합니다.

## 📝 todo
- [x] StoreDetail 진입시의 백버튼 위치 조절
- [x] PhotoDetail 쪽의 백버튼 크기 및 위치 조절
- [x] 리뷰 쓰고 돌아왔을때 리뷰 카운트 숫자가 변경되지 않던 것 수정
