### ISSUE TITLE
[Bug] MVP 이후 view관련 버그 수정 todo

### ISSUE THREAD

**Issue by sero3779** [YAPP-Github/21st-ALL-Rounder-Team-1-iOS#36]
## 📝 todo
- [x] imageView의 contentMode 수정하기
- [ ] collectionViewCell의 dynamic height 설정하기
- [x] auto layout 잘못 설정된 것 수정하기
