### ISSUE TITLE
[Bug] StoreDetail 화면에서 발생하는 버그 및 수정사항 반영

### ISSUE THREAD

**Issue by sero3779** [YAPP-Github/21st-ALL-Rounder-Team-1-iOS#98]
## 📝 todo
- [x] 긴 내용을 담고 있는 리뷰가 아님에도 셀 선택시 화면이 움직이는 문제 해결
- [x] 사진 자세히 보기 화면에서 하단에 탭바가 노출되는 문제 해결
- [x] 리뷰 작성 날짜가 영어로 노출되는 문제 해결
- [x] 상품 사진, 가격 제거
- [x] Cell Registration으로 리팩토링
- [ ] 레이아웃 콘솔 에러들 해결
